sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: RktkA2ME9y7na9jvpDNiJh0mGyJdqIGJP5M14yVLvqJaFxhD4fQNOO5jt1Y9lON0ZbkGcvQPDdqPC8QZJ0QhzERGDelMH8vm8r2UJEhVLypycbmv6ax8eKLARauLu5rMWRjqQYiF6pEiOoX6ZpObMn1l/N3r40iLSjtY1+OYaGm+6oFjh3NYDf2nkACdc+LTPNlhRyEXpRe9PbmEKeRLRTx1XMC9vUWLcSFSBfYrKcSLyxfux1Me0tVmI/erdJX8fVocPquGEvpt9/BuL5PSlugIPfFGO7U6WI7Nj7H3X6j76wAQPYdYdqELDZHXSHP/SE4wGv6HZkwnRhTpLnURFcHqolbOKocUajJjvwZLfqFhmVWH6Mgh/1MEDHklBdfOIr0ZneSf3daPHNAbPtVkdaNnu5RjxbBqtgkKyp/fG8ZRQ5Tkux0SPDdOQKcNWpt5I5yGfQSaiXto3cr6x7EHzrAvlDLewGoI3+8GrD/f/bbpMU+oR5Y52Rqoa9UQJEWlVFhW2QP5Sr3QbyBEB1iRuUbZoIpgE20NaPcjcZXiqivwABRzi3a0Dtx4yGvrRGfM8et2er/An/I2iM2Hengxjnt3qOI9zj//J99D3dqh6+tErfiBlTDqomAfHYq/Lv0Rwn/3STGv7A7KteXiAGuXqGaT1wKaDhf92cC0zacWMm4=
  - secure: x4+6xbkbFHyvjsEkT1OVfnLluqrLuLxJXzjQwbdydrGBaqnihgDWObVK6SSOaa/vNtrgJ+7PZ+cdHzL46XFLkZl36spJTmP9ET8cgWP3FsS1aJwWo8T0ws8+mkQ9ezTYeBTanpNYEMfKbWsbM3OuXYhDAm6lyZ3yEVJErwwEkANAok51U+mVAqYBjPbehtMD0fISui8A0xnG7yak0NB2VFQbGOgdwFtNXVDtYuDb9vXaPoc8CiW9DdFC26aoK08/4DuICtkJmsQE4Hn5Zh89AdwBB7OtbTv/VDXpAztagTDXiT6FSqDTeqLSatV1fWEw3HRFyLLXwou3G2NIlh5QuSao69kyGMHJSLzjch82ItRjAY8Wlujt1z7Ea5TIhksvJUWV55e/uDAUM1AG3Qjb+k5uCJw/ovNDwC3ahkDmwDhKwur4muA8lanaYI9p6RsiFpdt3564JRPSo3Bf9/clyRicFSZJQD9iUeh7b2ZHs0rQIEyetuas1SLT1buY0Clsxg91dnQCjB0TSb2bt+W604g7bZqA/X2DzZba2CSvvz+InNpcwhtpyeHyYrHIRVhNHLHyA4OY1W20xKtJikT9BZ5BxXUd/0ylHMBi5KWMU9KPJz32gkXN9Nu8qdnqKCXzbF9/6uHBqTqEZ7Z74IHaEiXxg0dwK4Eb0zIiIKA382s=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
